### ISSUE TITLE
Przekierowania nie są spójne z oryginałem

### ISSUE THREAD

**Issue by Marioneq4958** [wulkanowy/fake-log#53]
Fake-log w http://uonetplus.fakelog.cf/default/LoginEndpoint.aspx powinien przekierowywać do strony logowania, a zwraca informację o nieprawidłowym symbolu

**Comment by mklkj** [comment]
Bardzo możliwe, [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://makeapullrequest.com)
